export const SET_USER = "SET_USER";
export const SET_BOOKS = "SET_BOOKS";
export const SET_BOOKS_CONTROLLER = "SET_BOOKS_CONTROLLER";
export const SET_BOOKS_FOR_SEARCH = "SET_BOOKS_FOR_SEARCH";
export const SET_SEARCHED_BOOK = "SET_SEARCHED_BOOK";
